### ISSUE TITLE
你好 ，我在服务器上弄好后提示这个，是哪里错误啊？

### ISSUE THREAD

**Issue by yongjie9** [wdkang123/AutoFuckWM#12]
![image](https://user-images.githubusercontent.com/56878302/110433179-16049100-80eb-11eb-81a8-6d88cd6a11cf.png)

**Comment by wdkang123** [comment]
连接超时了吗？？

**检查以下这几点：**
1. mysql账号密码是否正确
2. mysql是否开启远程连接
3. mysql服务是否启动
4. mysql端口是否为3306（代码里我设置的默认是3306）
